  Session 3 

Task 1: 

1. 
Write a function to compute 5/0 and use try/except to catch the exceptions. 

In [18]:
def dash():
    try:
        a=5/0
    except:
        print('arithematic error')
    else:
        print(a)

In [20]:
dash()

arithematic error


2. 
 
Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 
 
Hint: Subject,Verb and Object should be declared in the program as shown below. 
 
subjects=["Americans ","Indians"] verbs=["play","watch"] objects=["Baseball","Cricket"] 
 
Output should come as below: 
 
Americans  play Baseball. Americans  play Cricket. Americans  watch Baseball. Americans  watch Cricket. Indians play Baseball. Indians play Cricket. Indians watch Baseball. Indians watch Cricket. 

In [22]:
subject=["Americans", "Indians"]
verb=["Play", "watch"]
obj=["Baseball","cricket"]

sentence_list = [(sub+" "+ vb + " " + ob) for sub in subject for vb in verb for ob in obj]
for sentence in sentence_list:
 print (sentence)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


Task 2: 
1.  
 
Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.  
 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre       
Theophile Vandermonde. 
 
 

In [2]:
import numpy as np
def compute_vander(array,power,incr):
    return np.vander(array,power,incr)
arr = [1,2,3,4]
print(compute_vander(arr,4,False))

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
